### ISSUE TITLE
error: RenameAcrossMountPoints

### ISSUE THREAD

**Issue by dominggo1999** [theseyan/bkg#1]
Is this something to do with how I set up bun and bkg on linux? I keep getting the same error, I have tried bkg v0.0.2 and v0.0.3, but still no luck.

```console
bkg ./ -o testing

No target was specified, building for x86_64-linux
Downloading bun-v0.4.0 for target x86_64-linux...
Runtime already exists, skipping
Downloading bkg runtime v0.0.4 for target x86_64-linux...
bkg runtime already exists, skipping
Building archive...
Writing file README.md with 221 bytes
Writing file tsconfig.json with 416 bytes
bun.lockb is executable
Writing file bun.lockb with 1187 bytes
Writing file package.json with 121 bytes
Writing directory node_modules
Writing directory node_modules/bun-types
Writing file node_modules/bun-types/README.md with 1017 bytes
Writing file node_modules/bun-types/types.d.ts with 1899784 bytes
Writing file node_modules/bun-types/package.json with 375 bytes
Writing file index.ts with 30 bytes
Configuration file not found, using default
Adding Bun binary...
Finalized archive
Compressing archive...
Compressed to 37711283 bytes
Calculated CRC32 hash: 483121177
Writing archive to binary...
Written 37711283 bytes to binary
Finalizing binary...
Done
error: RenameAcrossMountPoints

```

![image](https://user-images.githubusercontent.com/64012087/210073504-bc70fc15-e4b6-4335-aa8c-fbaf29dd36df.png)

**Comment by theseyan** [comment]
Are `/tmp` and `coding/bun-kai/test` on different mount points/filesystems?

**Comment by dominggo1999** [comment]
Yup, that's the the problem.

```console

bkg ./ -o /tmp/test
No target was specified, building for x86_64-linux
Downloading bun-v0.4.0 for target x86_64-linux...
Runtime already exists, skipping
Downloading bkg runtime v0.0.4 for target x86_64-linux...
bkg runtime already exists, skipping
Building archive...
Writing directory test
Writing file test/README.md with 221 bytes
Writing file test/tsconfig.json with 416 bytes
test/bun.lockb is executable
Writing file test/bun.lockb with 1187 bytes
Writing file test/package.json with 121 bytes
Writing directory test/node_modules
Writing directory test/node_modules/bun-types
Writing file test/node_modules/bun-types/README.md with 1017 bytes
Writing file test/node_modules/bun-types/types.d.ts with 1899784 bytes
Writing file test/node_modules/bun-types/package.json with 375 bytes
Writing file test/index.ts with 30 bytes
Writing file .gitignore with 2172 bytes
Configuration file not found, using default
Adding Bun binary...
Finalized archive
Compressing archive...
Compressed to 37712537 bytes
Calculated CRC32 hash: 565776911
Writing archive to binary...
Written 37712537 bytes to binary
Finalizing binary...
Done
⚡ Built test for target x86_64-linux.


```

**Comment by theseyan** [comment]
Fixed! Thanks for reporting 👍 
I've updated the release assets for `v0.0.4`, please reinstall and see if it fixes the issue.

**Comment by dominggo1999** [comment]
Now it's compiled successfully, but now I get another error  : 

 
![image](https://user-images.githubusercontent.com/64012087/210078647-b62322c8-0942-4652-a715-982b5a62fd1b.png)

![image](https://user-images.githubusercontent.com/64012087/210078686-fd15bbd2-e156-40ab-9fab-df63a2a4f57e.png)

**Comment by theseyan** [comment]
That happens because bkg expects the entrypoint of the application to be `index.js` by default when `bkg.config.json` is absent.

A quick workaround is create a `bkg.config.json` in the project root and set the `entry` key to `index.ts`.

This is stupid though, I'll probably add `index.ts` to default entrypoints 👍

**Comment by dominggo1999** [comment]
I've added bkg.config.json, and now this is what i get : 

![image](https://user-images.githubusercontent.com/64012087/210081959-1de557b5-c7da-42cd-a66c-fe80da2b9053.png)

![image](https://user-images.githubusercontent.com/64012087/210081987-373cbc7f-3145-4637-b494-4415b90fd6ae.png)

**Comment by theseyan** [comment]
I can't seem to be able to reproduce this.

Can you zip up the `test` folder and upload it so I can have a look?

**Comment by dominggo1999** [comment]
It's just the default project that is generated with ```bun init```.

https://github.com/dominggo1999/bkg-error-reproduction

even if there is only index.js file it still gives the error

![image](https://user-images.githubusercontent.com/64012087/210100619-9e2a6804-9dd1-4b4b-b109-5f6c4877b526.png)

**Comment by theseyan** [comment]
Looks like the embedded Bun runtime is crashing.
What happens if you run:
```
/tmp/.test_runtime_1058350503/bkg_bun /tmp/.test_runtime_1058350503/index.js
```
Does it crash or work correctly?
Also, what is the output of `cat /proc/cpuinfo | grep -o avx2`?

**Comment by dominggo1999** [comment]
there is no .test_runtime_1058350503/bkg_bun & .test_runtime_1058350503/index.js in ```/tmp```

![image](https://user-images.githubusercontent.com/64012087/210125374-a6f6dff1-4be0-41ee-878a-3dd2b0f65ea1.png)

**Comment by theseyan** [comment]
The empty output of `cat /proc/cpuinfo | grep -o avx2` means your CPU doesn't support AVX2.
Can you try running bkg with `--baseline` flag and see if it changes anything?

**Comment by dominggo1999** [comment]
It solved the error.

![image](https://user-images.githubusercontent.com/64012087/210126206-71abc4d5-7532-4794-aa02-a988d2385fee.png)

Thank you so much for responding to this issue 🙏

**Comment by theseyan** [comment]
Glad to see this issue solved!

bkg should really check for the support of AVX2 instructions at compile time to make this less confusing; you can be sure to see that in the next release.
