### ISSUE TITLE
error: module not found

### ISSUE THREAD

**Issue by mjp0** [theseyan/bkg#5]
I got the compilation to work but when I try to run the binary, I get the following error. Any ideas what's going wrong since the error message is just a bit vague ;)

```
error: module not found "/tmp/.test_runtime_3722025239/index.js"
The following command exited with error code 1:
error: CommandFailed
```

I'm running this on Ubuntu 20.04 in WSL2.

**Comment by paulocoghi** [comment]
I believe it would be less difficult to the maintainers to help if you provide reproducible details. In case it's too much code, could you publish on a repository?

**Comment by mjp0** [comment]
@paulocoghi That's the thing, I have literally one file called my cli.ts and it's literally one line: `console.log('TBD')` :D

**Comment by paulocoghi** [comment]
Good news. In my tests, I identified that only `index.js` works as a default entry point, and using any other file, like `index.ts`, will reproduce your error.

The solution is to inform `bkg` what your entry point is, by creating a `bkg.config.json` with the content:

```json
{
    "entry": "index.ts"
}
```

It will work properly, then.

**Comment by paulocoghi** [comment]
Feedback to maintainers. On [src/compiler.zig](https://github.com/theseyan/bkg/blob/main/src/compiler.zig), it would be interesting to not compile the project or give a warning when the entry point file doesn't exists.

**Comment by paulocoghi** [comment]
@mjp0 When possible, could you try the proposed solution and give a feedback?

**Comment by mjp0** [comment]
> @mjp0 When possible, could you try the proposed solution and give a feedback?

Works for me too.

**Comment by gtrabanco** [comment]
Also for me

**Comment by theseyan** [comment]
Hi, like @paulocoghi suggested, bkg assumes `index.js` to be the entry point of the application. This can be changed by creating a `bkg.config.json` at the root directory of your project:
```json
{
    "entry": "app.ts"
}
```

I definitely agree that the error message is vague; in a newer version bkg will refuse to compile if it can't find the entrypoint, with a more elegant message.
